config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'messages#index'
  # root to: 'pages#home'
  resources :messages do

    resources :message_attachments, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  # after_create :send_message_email, only: [:create]
  belongs_to :user
  has_many :message_attachments
  accepts_nested_attributes_for :message_attachments

  validates :topic, presence: true
  validates :description, presence: true

  mount_uploader :photo, PhotoUploader
  # after_save :check_metadata

  #  def check_metadata
  #   if self.photo.present? && self.photo.metadata.present?
  #     exif = self.photo.metadata["photo_metadata"]
  #     # ...
  #   end
  # end
end

# private

# def send_message_email
#   MessageMailer.message_email(self).deliver_now
# end

app/models/message_attachment.rb
class MessageAttachment < ApplicationRecord
  belongs_to :message
  mount_uploader :attachment, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/message_attachments_controller.rb
class MessageAttachmentsController < ApplicationController
  def new
    @message = Message.find(params[:message_id])
    @message_attachment = MessageAttachment.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    # @messages = Message.all
    @messages = policy_scope(Message)
  end

  def show
    @message = Message.find(params[:id])
    authorize @message
    @message_attachments = @message.message_attachments.all
    # @message_attachment = MessageAttachment.new
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: "messages/show", pdf: "Show", dpi: 300, page_size: 'Letter'}   # Excluding ".pdf" extension.
    end
  end

  def new
    @message = Message.new
    @message_attachment = @message.message_attachments.build
    # @message_attachment = MessageAttachment.new
    authorize @message
    authorize @message_attachment
  end

  def create
    @message = Message.new(message_params)
    @message.user = current_user
    authorize @message
    if @message.save
      params[:message_attachments]['attachment'].each do |a|
        @message_attachment = @message.message_attachments.create!(:attachment => a)
      end
      message_content = @message
      MessageMailer.message_email(message_content).deliver_now
      redirect_to messages_path
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:topic, :description, message_attachments_attributes: [:id, :message_id, :attachment])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%#= react_component("Navbar") %>
    <%= render 'shared/navbar' %>
    <%#= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/message_attachments/_form.html.erb
<%= simple_form_for [@message_attachment], remote: true do |message_attachment| %>
<%= message_attachment.input :photo %>
<%= message_attachment.input :photo_cache, as: :hidden %>
<% end %>

app/views/message_attachments/new.html.erb
<%= render "form" %>

app/views/messages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">


<h4>Your Messages</h4>

<% @messages.each do |message| %>
<div class="messages">

<ul>
  <li><%= link_to message.topic, message_path(message) %></li>
</ul>
</div>
<% end %>

<%#= react_component("HelloWorld", { greeting: "Hello from react-rails." }) %>


<%= button_to "New Message", new_message_path, method: :get, class: "button-style" %>
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">


<h1>New Message</h1>

<%= simple_form_for(@message) do |message| %>
<%= message.input :topic, collection: ["Contract", "Other"], selected: "contract" %>
<%= message.input :description, placeholder: "Enter Your Message" %>
<%#= message.input :photo %>
<%#= message.input :photo_cache, as: :hidden %>
<%= message.fields_for :message_attachments do |attachment| %>
<%= attachment.file_field :attachment, multiple: true, name: "message_attachments[attachment][]" %>
<% end %>
<%= message.submit "Send Message", class: "button-style" %>
<% end %>
    </div>
  </div>
</div>

app/views/messages/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">

    <h1><%= @message.topic %></h1>

<div class="message">

<h4>Description</h4>
  <%= @message.description %>
  <!-- <li><%#= cl_image_tag(@message.photo, width:100, height:100) %></li> -->

</div>


<div class="attachments">
<h4>Attachments</h4>
<% @message_attachments.each do |attachment| %>
<%= cl_image_tag(attachment.attachment_url, width:100, height:100) %>
<% end %>
</div>



<%#= render "message_attachments/form" %>

<%= button_to "Back", messages_path, method: :get, class: "button-style" %>
    </div>
  </div>
</div>

app/views/messages/show.pdf.erb
<!-- <html>
  <h1>Hola Mundo</h1>
  </html> -->

  <!doctype html>
  <html>
  <head>
    <meta charset='utf-8' />


  </head>
  <body onload='number_pages'>
    <div id="header">

    </div>
    <div id="content">

      <!-- <h1>Hello</h1>
      <%= @message.topic %>
      <h1><%= @message.topic %></h1>
      <ul>
        <li><%= @message.topic %></li>
        <li><%= @message.description %></li>
        <li><%= cl_image_tag(@message.photo, width:100, height:100) %></li>
      </ul> -->
      <% @message.message_attachments.each do |attachment| %>
      <%= cl_image_tag(attachment.attachment_in_database, width:2480, height:3508) %>
      <% end %>
    </div>
  </body>
  </html>

app/views/pages/home.html.erb
<%#= react_component("Navbar") %>
<%#= react_component("HelloWorld", { greeting: "Hello from react-rails." }) %>
<%#= react_component("Logo") %>
<%#= react_component("TextBox") %>
<%#= react_component("Button", buttonText: "Login") %>
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="text-box">
      <h4>The best document app</h4>
      <p>Upload and save your document easily</p>
      </div>
      <div class="authorization">
        <div class="link-login">
        <%= button_to "Login", new_user_session_path, class: "button-style" %>
        </div>
        <div class="link-sign-up">
        <%= link_to "Sign Up", new_user_registration_path, class: "link-style" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <%= image_tag("logo.svg") %>
      </a>
      <a class="navbar-brand-name" href="#">
        <h4>Docu App</h4>
      </a>
    </div>

      <div class="navbar-authentication">
        <% if user_signed_in? %>
        <h4>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-brand-name" %>
        </h4>
        <% else %>
        <h4>
          <%= link_to "Login", new_user_session_path, class: "navbar-brand-name" %>
        </h4>
        <% end %>
      </div>

  </div>
</nav>